development:
  adapter: mysql2
  database: cats
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
production:
  adapter: mysql2
  database: cats
  encoding: utf8
  host: cats.com
  port: 3306
  username: cats
  password: cats
